Requirement already satisfied: causal-conv1d in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (1.1.3.post1)
Requirement already satisfied: ninja in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from causal-conv1d) (1.11.1.1)
Requirement already satisfied: packaging in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from causal-conv1d) (22.0)
Requirement already satisfied: buildtools in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from causal-conv1d) (1.0.6)
Requirement already satisfied: torch in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from causal-conv1d) (1.13.1)
Requirement already satisfied: docopt in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from buildtools->causal-conv1d) (0.6.2)
Requirement already satisfied: jinja2 in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from buildtools->causal-conv1d) (3.1.2)
Requirement already satisfied: furl in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from buildtools->causal-conv1d) (2.1.3)
Requirement already satisfied: twisted in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from buildtools->causal-conv1d) (23.10.0)
Requirement already satisfied: redo in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from buildtools->causal-conv1d) (2.0.4)
Requirement already satisfied: requests in /ocean/projects/cis240002p/jhou/envs/clone/lib/python3.10/site-packages (from buildtools->causal-conv1d) (2.31.0)
Could not fetch URL https://pypi.org/simple/argparse/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/argparse/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://pypi.org/simple/buildtools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/buildtools/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
INFO: pip is looking at multiple versions of causal-conv1d to determine which version is compatible with other requirements. This could take a while.
Could not fetch URL https://pypi.org/simple/causal-conv1d/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/causal-conv1d/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
